my_list = []
print(my_list)
my_list.append(10)
print(my_list)
my_list.append(20)
print(my_list)
my_list.append(30)
print(my_list)  
my_list.append(40)
print(my_list)
my_list.insert(1, 15)
print(my_list)
another_list = [50, 60, 70]
my_list.extend(another_list)
print(my_list)
my_list.remove(70)
print(my_list)
my_list.sort()
print(my_list)
index_of_30 = my_list.index(30)
print(f"Index of 30: {index_of_30}")